version: '3.7'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: userhandler
    command: node app.js
    ports:
        - 8080:8080
  #   depends_on:
  #       - mongodb
  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb
  #   ports:
  #       - 27017:27017
